
export const GET_DOCTOR = "GET_DOCTOR"
export const POST_DOCTOR= "POST_DOCTOR"
export const LOADING_DOCTOR = "LOADING_DOCTOR"
export const ERROE_DOCTOR = "ERROE_DOCTOR"
export const DELETE_DOCTOR = "DELETE_DOCTOR"
export const UPDATE_DOCTOR = "UPDATE_DOCTOR"

